### ISSUE TITLE
Facing troubles with logs directory and Docker 

### ISSUE THREAD

**Issue by ginomessmer** [nathanielxd/MagicHomeAPI#1]
First of all, kudos to you for making such a library, been looking for this for .NET.

However, there's an issue when I try to instantiate a new Light object. It's not able to create the logs directory in Docker.

```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.IO.IOException: Invalid argument
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at MagicHome.Light..ctor(IPEndPoint endpoint)
```

https://github.com/nathanielxd/magic-home/blob/c44ac059b10bf167cd4ace197912618156f48b13/LightController/Light.cs#L80

**Suggestion**: Maybe provide an option to disable logs, or better: expose an event handler that gets invoked each time a new log message arrives. This way it's fully optional without any weird quirks.

**Comment by nathanielxd** [comment]
Sorry, I made the project quite a long time ago and it was also my first thing I ever posted on Github. I'll remake the whole library soon. There's a lot of pointless stuff in there.

**Comment by ginomessmer** [comment]
No worries, it's a great library nonetheless. I was able to create a custom library in the meantime based on your project that fixes this issue and implements a subset of features. Feel free to check it out: https://github.com/ginomessmer/magic-home-dotnet

If you want to collaborate or ask anything, feel free to contact me on Twitter or Telegram. Same nick as here.
