### ISSUE TITLE
Previous versions

### ISSUE THREAD

**Issue by deankevorkian** [nathanielxd/MagicHomeAPI#8]
Hi, I was using the 1.2.0 release in my project, upgraded to 1.4.0 but since I'm having problem with the release I want to go back to 1.2.0.
Could you mind uploading the 1.2.0 version to the NuGet repository?

**Comment by nathanielxd** [comment]
Hello, I listed the 1.2.0 release. Sorry for the inconvenience.

**Comment by deankevorkian** [comment]
No worries! Thank you very much.
I'll try to figure why we had issues and if I find anything I'll open a PR. Thanks again! :)
