### ISSUE TITLE
Addressable LED strip

### ISSUE THREAD

**Issue by icky7s** [nathanielxd/MagicHomeAPI#9]
I'm wondering if it's possible to change individual lights on addressable LED strips using this API, if it is how would I go about doing that?

**Comment by nathanielxd** [comment]
Sorry but I'm not too sure I understand what you're trying to achieve.

**Comment by icky7s** [comment]
My LED strip is addressable which allows me to change individual LEDs instead of the entire strip, I was wondering if it was possible to change a single LED using your API?

**Comment by nathanielxd** [comment]
Sorry but this only works with 3528 and 5050 led strips, which are not addressable. Does your led strip work with this app: https://play.google.com/store/apps/details?id=com.zengge.wifi ? This library only works on led strips that are normally controlled by that mobile application.

**Comment by icky7s** [comment]
They work with the app, the API works well with my lights too, but I just wanted to see if that feature was available. I'll see if I can figure out how to do it. Thanks for the wonderful API btw.
